services:
  rodatraden:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rodatraden
    ports:
      - "8000:8000"
    volumes:
      # Share same paths used in local development
      - ./mydatabase:/app/mydatabase
      - ./media:/app/media
      - ./static:/app/static
      - ./tf:/app/tf
      - ./rodatraden:/app/rodatraden
      - ./templates:/app/templates
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      gunicorn --bind 0.0.0.0:8000 --workers 3 tf.wsgi:application
      "
    restart: unless-stopped
