# Generated by Django 2.2.2 on 2019-07-02 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYears',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('title_eng', models.CharField(blank=True, max_length=250, null=True)),
                ('description_eng', models.CharField(blank=True, max_length=10000, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ects', models.DecimalField(decimal_places=1, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Category')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ects', models.DecimalField(decimal_places=1, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titel')),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('code', models.CharField(max_length=10)),
                ('ects', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Poäng')),
                ('approved', models.BooleanField(blank=True, default=True, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('title_eng', models.CharField(blank=True, max_length=250, null=True)),
                ('description_eng', models.CharField(blank=True, max_length=10000, null=True)),
                ('homepage_url', models.URLField(blank=True, null=True)),
                ('evaluation_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('categories', models.ManyToManyField(through='rodatraden.CategoryCourse', to='rodatraden.Category', verbose_name='Kategorier')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('title_eng', models.CharField(blank=True, max_length=250, null=True)),
                ('description_eng', models.CharField(blank=True, max_length=10000, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('title_eng', models.CharField(blank=True, max_length=250, null=True)),
                ('description_eng', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.CharField(blank=True, max_length=10000, null=True)),
                ('image', models.ImageField(upload_to='pages/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('ects', models.DecimalField(decimal_places=1, max_digits=3)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('start', models.IntegerField()),
                ('weeks', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('title_eng', models.CharField(blank=True, max_length=250, null=True)),
                ('description_eng', models.CharField(blank=True, max_length=10000, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('valid', models.BooleanField(blank=True, default=True, null=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('title_eng', models.CharField(blank=True, max_length=250, null=True)),
                ('description_eng', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateCourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ects', models.DecimalField(decimal_places=1, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Category')),
                ('private_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.PrivateCourse')),
            ],
        ),
        migrations.AddField(
            model_name='privatecourse',
            name='categories',
            field=models.ManyToManyField(through='rodatraden.PrivateCourseCategory', to='rodatraden.Category'),
        ),
        migrations.AddField(
            model_name='privatecourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curr_course', to='rodatraden.Course')),
                ('prereq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereq_course', to='rodatraden.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('ects', models.DecimalField(decimal_places=1, max_digits=4)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(through='rodatraden.CategoryExam', to='rodatraden.Category')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOccasion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='År')),
                ('start', models.IntegerField(verbose_name='TODO')),
                ('weeks', models.IntegerField(verbose_name='Längd')),
                ('official', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('homepage_url', models.URLField(blank=True, null=True)),
                ('evaluation_url', models.URLField(blank=True, null=True)),
                ('syllabus_url', models.URLField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Course', verbose_name='Kurs')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Department'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Level', verbose_name='Nivå'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(through='rodatraden.Prerequisite', to='rodatraden.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='tracks',
            field=models.ManyToManyField(blank=True, to='rodatraden.Track'),
        ),
        migrations.AddField(
            model_name='categoryexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Exam'),
        ),
        migrations.AddField(
            model_name='categorycourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Course'),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titel')),
                ('description', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Beskrivning')),
                ('start_year', models.IntegerField(verbose_name='Startår')),
                ('private', models.BooleanField(default=True, verbose_name='Privat')),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('courseoccasions', models.ManyToManyField(blank=True, to='rodatraden.CourseOccasion')),
                ('privatecourses', models.ManyToManyField(to='rodatraden.PrivateCourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
