# Generated by Django 2.2.1 on 2019-05-04 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYears',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('start_year', models.IntegerField()),
                ('private', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('title_eng', models.CharField(blank=True, max_length=50)),
                ('description_eng', models.CharField(blank=True, max_length=200)),
                ('abbreviation', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(upload_to='categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique_for_date='created_at')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ects', models.DecimalField(decimal_places=1, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Category')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ects', models.DecimalField(decimal_places=1, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('code', models.CharField(max_length=6)),
                ('ects', models.DecimalField(decimal_places=1, max_digits=3)),
                ('approved', models.BooleanField(default=True)),
                ('closed', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=50)),
                ('title_eng', models.CharField(blank=True, max_length=50)),
                ('description_eng', models.CharField(blank=True, max_length=200)),
                ('homepage_url', models.URLField(blank=True)),
                ('evaluation_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique_for_date='created_at')),
                ('categories', models.ManyToManyField(through='rodatraden.CategoryCourse', to='rodatraden.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('title_eng', models.CharField(blank=True, max_length=50)),
                ('description_eng', models.CharField(blank=True, max_length=200)),
                ('abbreviation', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('title_eng', models.CharField(blank=True, max_length=50)),
                ('description_eng', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='pages/%Y/%m/%d/')),
                ('slug', models.SlugField(unique_for_date='created_at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('ects', models.DecimalField(decimal_places=1, max_digits=3)),
                ('note', models.CharField(blank=True, max_length=50)),
                ('start', models.IntegerField()),
                ('weeks', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocks', models.ManyToManyField(to='rodatraden.Block')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('title_eng', models.CharField(blank=True, max_length=50)),
                ('description_eng', models.CharField(blank=True, max_length=200)),
                ('abbreviation', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique_for_date='created_at')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('valid', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('title_eng', models.CharField(blank=True, max_length=50)),
                ('description_eng', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateCourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ects', models.DecimalField(decimal_places=1, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Category')),
                ('private_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.PrivateCourse')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('ects', models.DecimalField(decimal_places=1, max_digits=3)),
                ('code', models.CharField(blank=True, max_length=6)),
                ('note', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(through='rodatraden.CategoryExam', to='rodatraden.Category')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOccasion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('start', models.IntegerField()),
                ('weeks', models.IntegerField()),
                ('official', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=50)),
                ('homepage_url', models.URLField(blank=True)),
                ('evaluation_url', models.URLField(blank=True)),
                ('syllabus_url', models.URLField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Department'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Level'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(related_name='_course_prerequisites_+', to='rodatraden.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='tracks',
            field=models.ManyToManyField(to='rodatraden.Track'),
        ),
        migrations.AddField(
            model_name='categoryexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Exam'),
        ),
        migrations.AddField(
            model_name='categorycourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Course'),
        ),
        migrations.AddField(
            model_name='block',
            name='courseoccasion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.CourseOccasion'),
        ),
        migrations.AddField(
            model_name='block',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
