# Generated by Django 2.2.3 on 2019-07-16 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Beskrivning')),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ects', models.DecimalField(decimal_places=1, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Category')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ects', models.DecimalField(decimal_places=1, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Kursnamn')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Beskrivning')),
                ('code', models.CharField(max_length=10, verbose_name='Kod')),
                ('ects', models.DecimalField(decimal_places=1, default='7.5', max_digits=3, verbose_name='Poäng')),
                ('approved', models.BooleanField(blank=True, default=True, null=True, verbose_name='Godkänd')),
                ('closed', models.BooleanField(default=False, verbose_name='Stängd')),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('homepage_url', models.URLField(blank=True, null=True, verbose_name='Hemsida')),
                ('evaluation_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('categories', models.ManyToManyField(blank=True, through='rodatraden.CategoryCourse', to='rodatraden.Category', verbose_name='Kategorier')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Beskrivning')),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Beskrivning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('ects', models.DecimalField(decimal_places=1, max_digits=3)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('weeks', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False)),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rodatraden.AcademicYear')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titel')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Beskrivning')),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True, verbose_name='Förkortning')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Bild')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254, verbose_name='Din mailadress')),
                ('subject', models.CharField(max_length=250, verbose_name='Ämne')),
                ('message', models.TextField(max_length=5000, verbose_name='Innehåll')),
                ('fixed', models.BooleanField(default=False, verbose_name='Hanterat')),
                ('note', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Kommentarer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Skapad')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Uppdaterad')),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('week', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('valid', models.BooleanField(blank=True, default=True, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Beskrivning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateCourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ects', models.DecimalField(decimal_places=1, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Category')),
                ('private_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.PrivateCourse')),
            ],
        ),
        migrations.AddField(
            model_name='privatecourse',
            name='categories',
            field=models.ManyToManyField(through='rodatraden.PrivateCourseCategory', to='rodatraden.Category'),
        ),
        migrations.AddField(
            model_name='privatecourse',
            name='time_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rodatraden.TimePeriod'),
        ),
        migrations.AddField(
            model_name='privatecourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curr_course', to='rodatraden.Course')),
                ('prereq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereq_course', to='rodatraden.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Examensnamn')),
                ('ects', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Poäng')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Beskrivning')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Skapad')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Senast uppdaterad')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('categories', models.ManyToManyField(blank=True, through='rodatraden.CategoryExam', to='rodatraden.Category')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOccasion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeks', models.IntegerField(verbose_name='Längd')),
                ('official', models.BooleanField(default=True, verbose_name='Godkänd')),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('homepage_url', models.URLField(blank=True, null=True)),
                ('evaluation_url', models.URLField(blank=True, null=True)),
                ('syllabus_url', models.URLField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('year', models.IntegerField()),
                ('start', models.IntegerField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.AcademicYear', verbose_name='År')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Course', verbose_name='Kurs')),
                ('time_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.TimePeriod', verbose_name='Läsperiod')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Department', verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Level', verbose_name='Nivå'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, through='rodatraden.Prerequisite', to='rodatraden.Course', verbose_name='Förkunskapskrav'),
        ),
        migrations.AddField(
            model_name='course',
            name='tracks',
            field=models.ManyToManyField(blank=True, to='rodatraden.Track', verbose_name='Spår'),
        ),
        migrations.AddField(
            model_name='categoryexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Exam'),
        ),
        migrations.AddField(
            model_name='categorycourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='recommended',
            field=models.ManyToManyField(blank=True, related_name='recommended_track', to='rodatraden.Track', verbose_name='Rekommenderad'),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titel')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Beskrivning')),
                ('start_year', models.IntegerField(default=2019, verbose_name='Startår')),
                ('private', models.BooleanField(default=True, verbose_name='Privat')),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False)),
                ('courseoccasions', models.ManyToManyField(blank=True, to='rodatraden.CourseOccasion')),
                ('privatecourses', models.ManyToManyField(to='rodatraden.PrivateCourse')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Track', verbose_name='Spår')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
