# Generated by Django 2.2.2 on 2019-06-18 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(through='rodatraden.CategoryCourse', to='rodatraden.Category', verbose_name='Kategorier'),
        ),
        migrations.AlterField(
            model_name='course',
            name='ects',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Poäng'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Level', verbose_name='Nivå'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Titel'),
        ),
    ]
