# Generated by Django 2.2.2 on 2019-07-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='start_year',
            field=models.IntegerField(default=2019, verbose_name='Startår'),
        ),
    ]
