# Generated by Django 2.2.2 on 2019-07-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courseoccasion',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='privatecourse',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
