# Generated by Django 2.2.2 on 2019-07-12 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatecourse',
            name='time_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rodatraden.TimePeriod'),
        ),
    ]
