# Generated by Django 2.2.1 on 2019-05-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='courseoccasion',
        ),
        migrations.AddField(
            model_name='block',
            name='courseoccasion',
            field=models.ManyToManyField(to='rodatraden.CourseOccasion'),
        ),
    ]
