# Generated by Django 2.2.2 on 2019-07-12 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0002_auto_20190712_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Track'),
        ),
    ]
