# Generated by Django 2.2.2 on 2019-07-10 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0002_auto_20190702_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='approved',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Godkänd'),
        ),
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(blank=True, through='rodatraden.CategoryCourse', to='rodatraden.Category', verbose_name='Kategorier'),
        ),
        migrations.AlterField(
            model_name='course',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Stängd'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Department', verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Beskrivning'),
        ),
        migrations.AlterField(
            model_name='course',
            name='ects',
            field=models.DecimalField(decimal_places=1, default='7.5', max_digits=3, verbose_name='Poäng'),
        ),
        migrations.AlterField(
            model_name='course',
            name='homepage_url',
            field=models.URLField(blank=True, null=True, verbose_name='Hemsida'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Level', verbose_name='Nivå'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, through='rodatraden.Prerequisite', to='rodatraden.Course', verbose_name='Förkunskapskrav'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Kursnamn'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tracks',
            field=models.ManyToManyField(blank=True, to='rodatraden.Track', verbose_name='Spår'),
        ),
    ]
