# Generated by Django 2.2.2 on 2019-07-16 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0002_auto_20190716_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='desc_eng',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_eng',
        ),
        migrations.RemoveField(
            model_name='course',
            name='desc_eng',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_eng',
        ),
        migrations.RemoveField(
            model_name='department',
            name='desc_eng',
        ),
        migrations.RemoveField(
            model_name='department',
            name='title_eng',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='year',
        ),
        migrations.RemoveField(
            model_name='level',
            name='desc_eng',
        ),
        migrations.RemoveField(
            model_name='level',
            name='title_eng',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='desc_eng',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title_eng',
        ),
        migrations.RemoveField(
            model_name='timeperiod',
            name='title_eng',
        ),
        migrations.RemoveField(
            model_name='track',
            name='desc_eng',
        ),
        migrations.RemoveField(
            model_name='track',
            name='title_eng',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='courseoccasion',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.AcademicYear', verbose_name='År'),
        ),
        migrations.AlterField(
            model_name='courseoccasion',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='courseoccasion',
            name='time_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.TimePeriod', verbose_name='Läsperiod'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
