# Generated by Django 2.2.2 on 2019-07-15 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0003_block_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='year',
        ),
        migrations.AlterField(
            model_name='block',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Track', verbose_name='Spår'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Skapad'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='ects',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Poäng'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Examensnamn'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Senast uppdaterad'),
        ),
    ]
