# Generated by Django 2.2.2 on 2019-07-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0003_auto_20190716_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tracks',
            field=models.ManyToManyField(blank=True, to='rodatraden.Track', verbose_name='Ingår'),
        ),
    ]
