# Generated by Django 2.2.2 on 2019-07-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0004_auto_20190715_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
