# Generated by Django 2.2.2 on 2019-07-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0004_auto_20190717_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoccasion',
            name='start',
        ),
        migrations.RemoveField(
            model_name='courseoccasion',
            name='year',
        ),
        migrations.RemoveField(
            model_name='privatecourse',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='privatecourse',
            name='time_period',
        ),
        migrations.AddField(
            model_name='privatecourse',
            name='start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatecourse',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privatecourse',
            name='weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
