# Generated by Django 2.2.2 on 2019-07-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0005_auto_20190717_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatecourse',
            name='start',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='privatecourse',
            name='weeks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='privatecourse',
            name='year',
            field=models.IntegerField(),
        ),
    ]
