# Generated by Django 2.2.2 on 2019-07-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0005_exam_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
