# Generated by Django 2.2.2 on 2019-07-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0006_auto_20190715_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Beskrivning'),
        ),
    ]
