# Generated by Django 2.2.2 on 2019-07-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0006_auto_20190717_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='evaluation_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privatecourse',
            name='ects',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Poäng'),
        ),
        migrations.AlterField(
            model_name='privatecourse',
            name='start',
            field=models.IntegerField(verbose_name='Startvecka'),
        ),
        migrations.AlterField(
            model_name='privatecourse',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Kursnamn'),
        ),
        migrations.AlterField(
            model_name='privatecourse',
            name='weeks',
            field=models.IntegerField(verbose_name='Längd'),
        ),
        migrations.AlterField(
            model_name='privatecourse',
            name='year',
            field=models.IntegerField(verbose_name='Startår'),
        ),
    ]
