# Generated by Django 2.2.2 on 2019-07-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0007_auto_20190718_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='evaluation_url',
            new_name='url',
        ),
    ]
