# Generated by Django 2.2.2 on 2019-07-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0007_exam_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description_eng',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_eng',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description_eng',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_eng',
        ),
        migrations.RemoveField(
            model_name='department',
            name='description_eng',
        ),
        migrations.RemoveField(
            model_name='department',
            name='title_eng',
        ),
        migrations.RemoveField(
            model_name='level',
            name='description_eng',
        ),
        migrations.RemoveField(
            model_name='level',
            name='title_eng',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description_eng',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title_eng',
        ),
        migrations.RemoveField(
            model_name='track',
            name='description_eng',
        ),
        migrations.RemoveField(
            model_name='track',
            name='title_eng',
        ),
        migrations.AlterField(
            model_name='block',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Beskrivning'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Beskrivning'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Beskrivning'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='categories',
            field=models.ManyToManyField(blank=True, through='rodatraden.CategoryExam', to='rodatraden.Category'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Beskrivning'),
        ),
        migrations.AlterField(
            model_name='level',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Beskrivning'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Beskrivning'),
        ),
        migrations.AlterField(
            model_name='track',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Beskrivning'),
        ),
    ]
