# Generated by Django 2.2.2 on 2019-07-18 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0008_auto_20190718_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'verbose_name': 'Akademiskt år', 'verbose_name_plural': 'Akademiska år'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Institut', 'verbose_name_plural': 'Institution'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Nivå', 'verbose_name_plural': 'Nivåer'},
        ),
        migrations.AlterModelOptions(
            name='timeperiod',
            options={'verbose_name': 'Tidsperiod', 'verbose_name_plural': 'Tidsperioder'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'Spår', 'verbose_name_plural': 'Spår'},
        ),
        migrations.AddField(
            model_name='block',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Exam', verbose_name='Examen'),
        ),
    ]
