# Generated by Django 2.2.2 on 2019-07-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0009_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='viewed',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='from_email',
            field=models.EmailField(max_length=254, verbose_name='Din mailadress'),
        ),
        migrations.AlterField(
            model_name='report',
            name='message',
            field=models.TextField(max_length=5000, verbose_name='Innehåll'),
        ),
        migrations.AlterField(
            model_name='report',
            name='subject',
            field=models.CharField(max_length=250, verbose_name='Ämne'),
        ),
    ]
