# Generated by Django 2.2.2 on 2019-07-18 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0009_auto_20190718_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodatraden.Exam', verbose_name='Examen'),
        ),
    ]
