# Generated by Django 2.2.2 on 2019-07-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0010_auto_20190716_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='viewed',
        ),
        migrations.AddField(
            model_name='report',
            name='read',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
