# Generated by Django 2.2.2 on 2019-07-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0011_auto_20190716_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='read',
            field=models.BooleanField(default=False, editable=False, verbose_name='Läst'),
        ),
    ]
