# Generated by Django 2.2.2 on 2019-07-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0012_auto_20190716_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
