# Generated by Django 2.2.2 on 2019-07-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodatraden', '0013_auto_20190716_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='read',
        ),
        migrations.AddField(
            model_name='report',
            name='fixed',
            field=models.BooleanField(default=False, verbose_name='Hanterat'),
        ),
        migrations.AddField(
            model_name='report',
            name='note',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Kommentarer'),
        ),
        migrations.AlterField(
            model_name='report',
            name='from_email',
            field=models.EmailField(editable=False, max_length=254, verbose_name='Din mailadress'),
        ),
        migrations.AlterField(
            model_name='report',
            name='message',
            field=models.TextField(editable=False, max_length=5000, verbose_name='Innehåll'),
        ),
        migrations.AlterField(
            model_name='report',
            name='subject',
            field=models.CharField(editable=False, max_length=250, verbose_name='Ämne'),
        ),
    ]
